CREATE DATABASE SHOPEE;
USE SHOPEE;

CREATE TABLE CATEGORY (
    CateID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CateName VARCHAR(100) NOT NULL
);


CREATE TABLE PRODUCT (
    ProID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ProName VARCHAR(100) NOT NULL,
    Price INT NOT NULL,
    CATEID INT NOT NULL,
    Quantity INT NOT NULL,
    FOREIGN KEY (CATEID)
        REFERENCES CATEGORY (CateID)
);


CREATE TABLE VARIANT (
    VaID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Color VARCHAR(20) NOT NULL,
    Size INT NOT NULL,
    PROID INT NOT NULL,
    FOREIGN KEY (PROID)
        REFERENCES PRODUCT (ProID)
);


CREATE TABLE ADDRESS (
    AddID INT NOT NULL AUTO_INCREMENT PRIMARY KEY
);


CREATE TABLE USER (
	UserID  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    PassWord VARCHAR(100) NOT NULL,
    ADDID VARCHAR(100) NOT NULL,
    FOREIGN KEY (ADDID)
        REFERENCES ADDRESS (AddID)
);


CREATE TABLE CART (
    CartID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERID INT NOT NULL UNIQUE,
    TOTAL_PRICE INT NOT NULL,
    FOREIGN KEY (USERID)
        REFERENCES USER (UserID)
);


CREATE TABLE CART_LINE (
    LineID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CARTID INT NOT NULL,
    PRODUCTID INT NOT NULL,
    QUANTITY INT NOT NULL,
    TOTAL_PRICE INT NOT NULL,
    FOREIGN KEY (CARTID)
        REFERENCES CART (CartID),
    FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT (ProID)
);